include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Add:flutter_lints/flutter.yaml` tells your project to follow the standard Google/Flutter guidelines. If the package is missing from your `pubspec.yaml`, the file doesn't know where to find those rules.