import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'theme.dart';
import 'models/study_models.dart';
import 'course_detail_page.dart';

void main() async {
  // Ensure Flutter is initialized before anything else
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Hive and register adapters generated by build_runner
  await Hive.initFlutter();
  
  // These adapters were created during your successful 'dart run build_runner build'
  Hive.registerAdapter(TopicAdapter());
  Hive.registerAdapter(CourseUnitAdapter());
  
  // Open the offline storage box
  await Hive.openBox<CourseUnit>('courses');
  
  runApp(const NursingApp());
}

class NursingApp extends StatelessWidget {
  const NursingApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'GILBERT_STUDY',
      debugShowCheckedModeBanner: false,
      // Using our custom Navy & Classical theme
      theme: AppTheme.darkTheme,
      home: const HomeScreen(),
    );
  }
}

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  late Box<CourseUnit> courseBox;

  @override
  void initState() {
    super.initState();
    // Access the already opened box
    courseBox = Hive.box<CourseUnit>('courses');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // Gradient background for the "Deep Tech" feel
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [AppTheme.navyBlue, AppTheme.navyPurple],
          ),
        ),
        child: SafeArea(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const SizedBox(height: 40),
                const Text(
                  "COMMAND CENTER",
                  style: TextStyle(
                    fontSize: 28,
                    fontWeight: FontWeight.bold,
                    letterSpacing: 3,
                    color: AppTheme.marbleWhite,
                  ),
                ),
                const Text(
                  "Year One | Semester One",
                  style: TextStyle(color: Colors.grey, fontSize: 14, letterSpacing: 1),
                ),
                const SizedBox(height: 30),
                
                // Elevated "ADD COURSE" Selection Button
                GestureDetector(
                  onTap: () => _showAddCourseDialog(),
                  child: Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(22),
                    decoration: AppTheme.elevatedDecoration,
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(Icons.add_circle_outline, color: AppTheme.neonPurple),
                        const SizedBox(width: 12),
                        Text(
                          "ADD NEW COURSE UNIT", 
                          style: TextStyle(
                            fontWeight: FontWeight.bold, 
                            color: AppTheme.marbleWhite.withOpacity(0.9),
                            letterSpacing: 1,
                          )
                        ),
                      ],
                    ),
                  ),
                ),
                
                const SizedBox(height: 35),
                
                // The dynamic list of courses
                Expanded(
                  child: ValueListenableBuilder(
                    valueListenable: courseBox.listenable(),
                    builder: (context, Box<CourseUnit> box, _) {
                      if (box.isEmpty) {
                        return const Center(
                          child: Text(
                            "No missions assigned.\nAdd a course unit to begin.",
                            textAlign: TextAlign.center,
                            style: TextStyle(color: Colors.grey),
                          ),
                        );
                      }
                      return ListView.builder(
                        physics: const BouncingScrollPhysics(),
                        itemCount: box.length,
                        itemBuilder: (context, index) {
                          final course = box.getAt(index);
                          return _buildCourseCard(course!, index);
                        },
                      );
                    },
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  // Individual Course Selection Button
  Widget _buildCourseCard(CourseUnit course, int index) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 22),
      child: GestureDetector(
        onTap: () {
          // Navigating to the detail page we created earlier
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (context) => CourseDetailPage(courseIndex: index),
            ),
          );
        },
        child: Container(
          padding: const EdgeInsets.symmetric(vertical: 20, horizontal: 15),
          decoration: AppTheme.elevatedDecoration,
          child: ListTile(
            contentPadding: EdgeInsets.zero,
            title: Text(
              course.name.toUpperCase(), 
              style: const TextStyle(fontWeight: FontWeight.bold, letterSpacing: 1.5)
            ),
            subtitle: Padding(
              padding: const EdgeInsets.only(top: 8.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  LinearProgressIndicator(
                    value: course.progress,
                    backgroundColor: Colors.white10,
                    color: AppTheme.neonPurple,
                    minHeight: 4,
                  ),
                  const SizedBox(height: 8),
                  Text(
                    "${(course.progress * 100).toInt()}% READY FOR EXAMS",
                    style: const TextStyle(fontSize: 10, color: AppTheme.neonPurple, fontWeight: FontWeight.bold),
                  ),
                ],
              ),
            ),
            trailing: const Icon(Icons.chevron_right, color: AppTheme.neonPurple),
          ),
        ),
      ),
    );
  }

  void _showAddCourseDialog() {
    final controller = TextEditingController();
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: AppTheme.navyBlue,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(15)),
        title: const Text("INITIALIZE UNIT", style: TextStyle(letterSpacing: 1)),
        content: TextField(
          controller: controller,
          style: const TextStyle(color: Colors.white),
          decoration: const InputDecoration(
            hintText: "e.g. Microbiology",
            hintStyle: TextStyle(color: Colors.white24),
            enabledBorder: UnderlineInputBorder(borderSide: BorderSide(color: AppTheme.neonPurple)),
          ),
          autofocus: true,
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context), 
            child: const Text("ABORT", style: TextStyle(color: Colors.grey))
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(backgroundColor: AppTheme.neonPurple),
            onPressed: () {
              if (controller.text.isNotEmpty) {
                // Manually add the unit to Hive storage
                courseBox.add(CourseUnit(name: controller.text, topics: []));
                Navigator.pop(context);
              }
            },
            child: const Text("INITIALIZE"),
          ),
        ],
      ),
    );
  }
}